[package]
name = "gcodeparse"
version = "0.1.0"
authors = ["Simon Walker <s.r.walker101@googlemail.com>"]

[dependencies]
failure = "0.1.1"
serde_derive = "1.0.43"
serde = "1.0.43"
csv = "1.0.0-beta.5"
